CREATE DATABASE radio;
CREATE TABLE contacto (id INT NOT NULL PRIMARY KEY, nombre VARCHAR (100) NOT NULL, email VARCHAR (250) NOT NULL, mensaje VARCHAR (400) NOT NULL);
CREATE TABLE pedidos (id INT NOT NULL PRIMARY KEY, nombre VARCHAR (100) NOT NULL, artista VARCHAR (100) NOT NULL, comentario VARCHAR(200) NOT NULL);
CREATE TABLE live_chat (id INT NOT NULL PRIMARY KEY, nombre VARCHAR (100) NOT NULL, mensaje VARCHAR (400) NOT NULL);